// <auto-generated />
using System;
using Gnosis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gnosis.Infrastructure.Migrations
{
    [DbContext(typeof(GnosisDbContext))]
    [Migration("20260801035140_InicialConBloquesTiempo")]
    partial class InicialConBloquesTiempo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gnosis.Domain.Entities.BloqueTiempo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TareaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.ToTable("BloquesTiempo", (string)null);
                });

            modelBuilder.Entity("Gnosis.Domain.Entities.SesionEnfoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SesionesEnfoque", (string)null);
                });

            modelBuilder.Entity("Gnosis.Domain.Entities.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompletada")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TareaPadreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TareaPadreId");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("Gnosis.Domain.Entities.BloqueTiempo", b =>
                {
                    b.HasOne("Gnosis.Domain.Entities.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Gnosis.Domain.Entities.Tarea", b =>
                {
                    b.HasOne("Gnosis.Domain.Entities.Tarea", "TareaPadre")
                        .WithMany("Subtareas")
                        .HasForeignKey("TareaPadreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TareaPadre");
                });

            modelBuilder.Entity("Gnosis.Domain.Entities.Tarea", b =>
                {
                    b.Navigation("Subtareas");
                });
#pragma warning restore 612, 618
        }
    }
}
